Check UID & GID of "domjudge" are same across Docker build stages
Since commit b6ae2719d4 (Preserve ownership of /opt/domjudge set by
`make install-*`, 2024-07-10), the ownership of the files copied from
the previous build stage is preserved rather than overwritten. This is
slightly fragile because Docker's `COPY --from` directive only
preserves the ownership correctly if the numerical user and group IDs
are the same across the build stages.

This commit adds a check to verify that the IDs of the "domjudge" user
are the same. (We don't need to check the IDs of the "www-data" user,
because they're guaranteed to be the same.[1][2])

 - For the domserver image, we do this by comparing the values in
   /etc/passwd.

 - For the judgehost image, we can't compare /etc/passwd because the
   first build stage is in a separate Dockerfile (chroot-and-tar.sh
   needs to run in a privileged container). So instead we check the
   owner of a well-known directory (/opt/domjudge/judgehost/run) which
   should be owned by "domjudge". (We can't check the GID because
   there are no files or directories with group "domjudge".)

This commit also moves the creation of the "domjudge" user a little
earlier, to reduce the opportunity for some other command to create a
user and change the ID assigned to the "domjudge" user.

(An alternative approach that guarantees the ownership is preserved,
regardless of the UID & GID, is to create a tarball, copy the tarball
between the build stages, then extract the tarball. This is reliable
because GNU tar records the user name and attempts to preserve it when
extracting. However it's slower and makes the image larger.)

[1] https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes
[2] https://salsa.debian.org/debian/base-passwd/blob/master/passwd.master

diff --git a/docker/domserver/Dockerfile b/docker/domserver/Dockerfile
--- a/docker/domserver/Dockerfile
+++ b/docker/domserver/Dockerfile
@@ -3,6 +3,9 @@ LABEL org.opencontainers.image.authors="DOMjudge team <team@domjudge.org>"
 
 ENV DEBIAN_FRONTEND=noninteractive
 
+# Set up user
+RUN useradd -m domjudge
+
 # Install required packages for build of domserver
 RUN apt-get update \
 	&& apt-get install --no-install-recommends --no-install-suggests -y \
@@ -21,9 +24,6 @@ RUN apt-get update \
 
 # Use venv to install latest Sphinx. 6.1.0 or higher is required to build DOMjudge docs.
 RUN python3 -m venv /venv && . /venv/bin/activate && pip3 install sphinx sphinx-rtd-theme rst2pdf
-
-# Set up user
-RUN useradd -m domjudge
 
 # Install composer
 RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
@@ -69,6 +69,14 @@ RUN apt-get update \
 RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 	&& php composer-setup.php \
 	&& mv /composer.phar /usr/local/bin/composer
+
+# Check the UID and GID of the domjudge user are the same as in the previous build stage
+# (otherwise the COPY directives below won't set the correct ownership)
+COPY --from=domserver-build /etc/passwd /tmp/domserver-build-etc-passwd
+RUN sed -i -n '/^domjudge:/p' /tmp/domserver-build-etc-passwd \
+	&& sed -n '/^domjudge:/p' /etc/passwd | diff /tmp/domserver-build-etc-passwd - \
+	|| { echo "error: UID/GID of 'domjudge' differ from previous build stage; they must be the same for COPY to work" >&2; exit 1; } \
+	&& rm /tmp/domserver-build-etc-passwd
 
 # Copy domserver
 COPY --from=domserver-build /opt/domjudge/domserver /opt/domjudge/domserver
